### ISSUE TITLE
Hello~Bassman2 :) How can I get some values?

### ISSUE THREAD

**Issue by 18photos** [Bassman2/MediaDevices#1]
Hello. I like your MTP Library.

But I can't get some value..

That is..
1. Size of total Storage. 
2. Size of free Storage.

I was replace your some code, but there are not connected error..

If you can add this logic, I feel so good.

Thank you Bass man.

1. public static PropertyKey WPD_STORAGE_CAPACITY = new PropertyKey(0x01A3057A, 0x74D6, 0x4E80, 0xBE, 0xA7, 0xDC, 0x4C, 0x21, 0x2C, 0xE5, 0x0A, 4);

2. public static PropertyKey WPD_STORAGE_FREE_SPACE_IN_BYTES = new PropertyKey(0x01A3057A, 0x74D6, 0x4E80, 0xBE, 0xA7, 0xDC, 0x4C, 0x21, 0x2C, 0xE5, 0x0A, 5);

**Comment by Bassman2** [comment]
Hi 18photos,

GetStorageInfo is added now to get the size of total and free storage.

Regards,
  Ralf

**Comment by 18photos** [comment]
Very nice Bassman2.
I am going to my home.
I will take your library.
Your library is very simple and compotable but have many importable function.
Thank you. 
Take care :)
