### ISSUE TITLE
MediaDevices.GetDevices() does not refresh

### ISSUE THREAD

**Issue by gwatts83** [Bassman2/MediaDevices#11]
Hi i have recently started using this library and its great and easy to use. The only issue i have had is that the list of attached devices returned by MediaDevices.GetDevices() does not update if a device is plugged in/removed while my application is running.
I also get an error when i mount a drive after launching the application (null exception while enumerating GetDrives()

Cheers

**Comment by Bassman2** [comment]
Hi, the detection of whether a device was plugged in or removed is not part of the COM interface that I use for Media Devices. For this purpose you can use my other project WpfUsbMonitor.
https://github.com/Bassman2/WpfUsbMonitor
