### ISSUE TITLE
MediaDevice.GetDevices() returns incomplete MediaDevice-Objects

### ISSUE THREAD

**Issue by hwagent** [Bassman2/MediaDevices#12]
We are calling MediaDevice.GetDevices() in our program from different threads (but never at the same time) and have noticed that only the first call (from the main thread) provides a complete list of all connected (Android) devices. Although all subsequent calls return a list with the correct number of MediaDevice objects, only the first object of this list is completely filled/initialized correctly. All subsequent objects are uninitialized, the DeviceId and Manufacturer fields are null.

Does something have to be considered when calling MediaDevice.GetDevices() from different threads?

**Comment by hwagent** [comment]
I just noticed that the problem also occurs when MediaDevice.GetDevices() is called from the EventArrived-EventHandler of the ManagementEventWatcher class.

If two devices are connected and a device is disconnected, we call the MediaDevice.GetDevices() method directly from the EventArrived-EventHandler. The MediaDevice object returned by this method is not completely initialized, e.g. the Manufacturer field contains this string instead of the manufacturer: "M\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"

**Comment by cessna048** [comment]
Which apartment model is required?
