### ISSUE TITLE
MediaDeviceEventArgs how to use

### ISSUE THREAD

**Issue by leeand27** [Bassman2/MediaDevices#131]
If I want to use OperationProgress Property in relation to DownloadFile Method of a MediaDevice -
how would I do that? I assume this would be by handling an event - but I can not find that event in the MediaDevice Class. How do I use the MediaDeviceEventArgs Class?
A simple example would be appreciated - in my case it is coded C# in Windows Forms.

**Comment by NilsHoyer** [comment]
Unfortunately, it looks like, Ralf does not support this project at the moment. May I ask to answer your question?

The `MediaDeviceEventArgs` class will be used with the `MediaDevice` events only. But the `DownloadFile` method does not trigger an event. So you can't use the `OperationProgress` at the moment.

**Comment by leeand27** [comment]
Thank you Nils for the clarification.
