### ISSUE TITLE
EnumerateFiles() multiple filters

### ISSUE THREAD

**Issue by ITaluone** [Bassman2/MediaDevices#14]
Hi Ralf

First: great work! Thanks a lot.

Now my "problem":
I have to find and grab all multimedia files (mp4, mp3, jpg, png, gif, wav, ...). 
With the given method _EnumerateFiles()_ I only able to search for one extension at a time. e.g. _device.GetRootDirectory().EnumerateFiles("*.jpg")_. That means I have to do that more or less manually for all files I want to grab.

It would be nice, if there is a way to do it like this: 
_device.GetRootDirectory().EnumerateFiles("\*.jpg|\*.png|\*.mp4")_ 
or
_device.GetRootDirectory().EnumerateFiles(new string[] { "\*.jpg", "\*.png" })_

Thanks for your service

**Comment by Bassman2** [comment]
Hello,

Did you try that? The first version should work. The search expression is put into a regurar expression and "|" is not changed. So it should work as an OR.

Greeting
   Ralf

**Comment by ITaluone** [comment]
Hi :)

Thanks for your reply.

But in the comments before "EnumerateFiles()" it says: "_...but doesn't support regular expressions_".

Did that mean not to pass a "Regex"-object into the method?

**Comment by Bassman2** [comment]
That's correct.

It should have the same syntax as System.IO.Directory.EnumerateFiles.
Internally, however, the searchPattern is converted to a regular expression.

```
        internal static string FilterToRegex(string filter)
        {
            if (filter == null || filter == "*" || filter == "*.*")
            {
                return null;
            }

            StringBuilder s = new StringBuilder(Path.GetFileName(filter));
            s.Replace(".", @"\.");
            s.Replace("+", @"\+");
            s.Replace("$", @"\$");
            s.Replace("(", @"\(");
            s.Replace(")", @"\)");
            s.Replace("[", @"\[");
            s.Replace("]", @"\]");
            s.Replace("?", ".?");
            s.Replace("*", ".*");
            return s.ToString();
        }
```


So `"*.png|*.gif"` is converted to `".*\.png|.*\.gif"`

**Comment by ITaluone** [comment]
ok, thanks.

that helped!

**Comment by anothertal3** [comment]
@ITaluone Out of curiosity: did this work for you? When I try to set different filters e.g. `*.png|*.gif` I receive the following error from within the `Path.GetFileName(filter)` part in `FilterToRegex`:

```System.ArgumentException: 'Illegal characters in path.'```

Without this command it still seems to work just fine?

**Comment by ITaluone** [comment]
Hi,

this is weird... the last time i tried it with the code above, this solution worked.

Now I get this same exception
