### ISSUE TITLE
Question: Download file with progress?

### ISSUE THREAD

**Issue by philllipmunn** [Bassman2/MediaDevices#16]
Awesome library - I have a quick question:

I'm using MediaDevices.DownloadFile() to download video files from a device. Sometimes these files can be rather large, upto 1GB in size. I'd love to know, is there any way to get download progress from the device?

If there's any way of having a callback to report download progress - that would be awesome or if you can even point me to where I might be able to add this to your project, be happy to write and submit a pull request.

**Comment by Darkyenus** [comment]
I am not sure if there is an API for it on the low level, but you could try tracking how many bytes did you already receive through the download stream. Divide that by the file size (which you can get before starting the download) and you get yourself a progress percentage.

**Comment by philllipmunn** [comment]
Thank you so much both of you for the advice. @Bassman2 your example is greatly appreciated, and I now have something similar in my project working which allows me to watch the file transfer progress in more detail. ☕ Thanks again!

**Comment by Bassman2** [comment]
Hi Phillip,

Thanks for the coffee.

Ralf

Von: philllipmunn <notifications@github.com>
Gesendet: Dienstag, 29. Januar 2019 00:35
An: Bassman2/MediaDevices <MediaDevices@noreply.github.com>
Cc: Ralf Beckers <ralf.beckers@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [Bassman2/MediaDevices] Question: Download file with progress? (#16)


Thank you so much both of you for the advice. @Bassman2<https://github.com/Bassman2> your example is greatly appreciated, and I now have something similar in my project working which allows me to watch the file transfer progress in more detail. ☕ Thanks again!
