### ISSUE TITLE
2 feature questions

### ISSUE THREAD

**Issue by Troillius** [Bassman2/MediaDevices#17]
Hi Bassman2,
first of all thank you very much for that awesom library.

I have to questions for you:
1. I would like to access the IMEI No of smartphones that are connected to my pc. Do you have any idea how to get the number?
2. I*d also like to open the windows explorer on a specific directory of the smartphone. Can I achieve this somehow with your library?

Thank you again

**Comment by Bassman2** [comment]
Hello Troillius,

to your questions:

1. I have not found a MTP property with the IMEI No with my devices. 
With Android you can probably read the No from a file. 
This can be done with my library but does not have its own function.

2. The path can easily be assembled by yourself and then the Explorer can be called up.

e.g. "This PC\Ralf Phone\Phone\Documents\UploadTree"
Where "This PC" is fixed and can be also in another language, 
"Ralf Phone" is the friendly name of the device and the rest is the local path you use also in the library.

Regards
 Ralf

**Comment by Troillius** [comment]
Hi Ralf,
thank you for the reply.
Concerning point 2: I did try this and while pasting the path in an open explorer and then navigating to it works perfectly fine, if I try to call the explorer with the same path frome code it is not working.

So if you have any more ideas I'd be very gratefull.

Regards
Sebastian

**Comment by Bassman2** [comment]
Hi Sebastin,

you can try something like 
explorer shell:::{35786D3C-B075-49b9-88DD-029876E11C01}

Regards
Ralf
