### ISSUE TITLE
Question: .NET Core compatibility?

### ISSUE THREAD

**Issue by 1jibber** [Bassman2/MediaDevices#18]
Hi! Are you planning on making a .NET Core version of your library? Thanks

**Comment by Bassman2** [comment]
Hi! Currently I'm not planning to make a .NET Core version, because this library is only a wrapper for the Windows MTP COM interface and it will not run outside Windows. I will make a try if Core 3.0 is finally released.

**Comment by Bassman2** [comment]
Hi! I started create a .NET Core version of my library. It's available in the "core" branch. Feel free to test it.

**Comment by 1jibber** [comment]
Great thanks - works a treat in Core 2.2 app.  👍
