### ISSUE TITLE
How to distinguish between phone or USB or tab connected on USB port

### ISSUE THREAD

**Issue by PallaviGarg7** [Bassman2/MediaDevices#19]
Hi,

I need to filter out only mobile devices ie, android phones connected on USB port. I tried using MediaDevice.DeviceType, but it does not give "DeviceType.Phone" value.
For onePlus, pen drive it gave - DeviceType.Generic
For Samsung phone it gave - DeviceType.MediaPlayer

Is there any way to actually filter these devices?

Best
Pallavi

**Comment by Bassman2** [comment]
Hello,

the DeviceType is a value that the OEM sets for its device. I have no influence on that. For Android devices, the value also changes depending on the setting of the USB connection. A real query whether it is a mobile phone is not known to me.

Best 
Ralf
