### ISSUE TITLE
MediaDevices.dll does not represent a strongly named assembly

### ISSUE THREAD

**Issue by PallaviGarg7** [Bassman2/MediaDevices#20]
Hi Ralf,

I need to have MediaDevices package to be a strongly named assembly. Is there any signed version available? If not, how do you suggest to sign it?

Thanks & Regards,
Pallavi Garg

**Comment by PallaviGarg7** [comment]
Hi Ralf,

Is there any update on this?

Regards
Pallavi

**Comment by PallaviGarg7** [comment]
Hi Ralf,

Is there any update on this?

Regards
Pallavi

**Comment by Bassman2** [comment]
Hello Pallavi,

what kind of signing do you mean?

On the one hand, you can sign the assembly with a self-made certificate (sn -k <file name>) that does not give you high security and on the other hand you can buy a code signing certificate. This costs a few hundred dollars a year that I do not want to pay.

Why do not you take the DLL and sign it yourself?
al /out:<assemblyName> <moduleName> /keyfile:<keyfileName>

Ralf

**Comment by chcg** [comment]
See https://docs.microsoft.com/en-us/dotnet/standard/assembly/enhanced-strong-naming

> However, strong name keys don’t contain any reliable information about the publisher, nor do they contain a certificate hierarchy. A strong name signature does not guarantee the trustworthiness of the person who signed the assembly or indicate whether that person was a legitimate owner of the key; it indicates only that the owner of the key signed the assembly. Therefore, we do not recommend using a strong name signature as a security validator for trusting third-party code. Microsoft Authenticode is the recommended way to authenticate code.

**Comment by PallaviGarg7** [comment]
Thanks Ralf for your reply!
We need signing not for security but identity so no monitory cost is involved if you do it.
Please refer to this: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming
Can you please make a signed version available?

**Comment by Bassman2** [comment]
You can find the strong name file in the Signed folder.

**Comment by PallaviGarg7** [comment]
Thank you so much Ralf. I am closing this issue.
