### ISSUE TITLE
ToUlong does not work for value type VT_UI4”

### ISSUE THREAD

**Issue by h4z0rQ** [Bassman2/MediaDevices#24]
Getting this exception when access to Windows Embedded CE 7.0 files. Directories return ok.

![pp](https://user-images.githubusercontent.com/29544857/69534541-52ee5800-0f7a-11ea-8dd5-a08f70b9241f.PNG)

**Comment by Bassman2** [comment]
Fixed

**Comment by h4z0rQ** [comment]
If you could update signed version or nuget package.
