### ISSUE TITLE
Access Violation Exception (0xc0000005) 

### ISSUE THREAD

**Issue by PallaviGarg7** [Bassman2/MediaDevices#26]
Hi,

We are using imobiledevice-net to detect any usb device connection via usb port. Please refer to below log from Event Viewer. We use ManagementEventWatcher to detect device attachment.

Application was running and this fatal issue happened just after connecting device with system. This is not very frequent issue, so won’t be able to provide more details.
If someone has fixed or handled this issue, please let us know. Any help would be much appreciated!

Log-
Faulting application name: DummyName.exe, version: 1.1.2.54, time stamp: 0x5dd3fe20
Faulting module name: PresentationCore.ni.dll, version: 4.8.4018.0, time stamp: 0x5d4a6c7c
Exception code: 0xc0000005
Fault offset: 0x0067876d
Faulting process id: 0x3050
Faulting application start time: 0x01d5a3a6a32299f8
Faulting application path: C:\Program Files (x86)\DummyName.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\PresentationCore\431135a1fa749be763773e77963c87b4\PresentationCore.ni.dll
Report Id: 8cffc963-5e5f-4fca-adbf-f2dc3244f83c

Thanks
Pallavi Garg

**Comment by Bassman2** [comment]
Wrong repository.

**Comment by PallaviGarg7** [comment]
Hi Bassman2,

We faced this issue with two different libraries. Have updated the description. Could you please help us with this.

Thanks
Pallavi
