### ISSUE TITLE
Vendor extensions

### ISSUE THREAD

**Issue by lukazlatecan** [Bassman2/MediaDevices#28]
I am trying to use this library to send 0x101B (GetPartialObject) request to MTP device and than read the data. I can't find the way to do that. What the inputParams should be? How to read the received data?
Thank you.

**Comment by Bassman2** [comment]
Hi Luka,

check the Vendor… methods in the MediaDevice class.
Some are commented out because I found no device to test it.
Feel free to test it and send me your changes.

Regards,
  Ralf
