### ISSUE TITLE
API hangs when accessing file path after FileDelete method.

### ISSUE THREAD

**Issue by kiloecho2** [Bassman2/MediaDevices#30]
Hi,
I'm using MediaDevices 1.8.0 on .NET 4.5, connected MTP devices are Android phones (tried Android 4.3, 7.0 and 9).
API hangs are discovered in the following situations, when trying to access a filepath after its file has been deleted:

Example 1:
`MediaDevice.DeleteFile(filepath)`
`if MediaDevice.FileExists(filepath) then ...`

The DeleteFile method will correctly delete the file on the device but the FileExists method will not produce a result nor an exception. Instead program execution goes into hang within the method.
Eventually the processing will continue after 3 minutes or so but typically nothing happens for at least 5 minutes.
Same behaviour has been observed when the UploadFile method is used after the DeleteFile.

Interestingly, renaming the file before delete will not help.
Example 2:
`MediaDevice.RenameFile(filepath, newfilename)`
`MediaDevice.DeleteFile(newfilepath)`
`if MediaDevice.FileExists(filepath) then ...`

RenameFile renames the file and DeleteFile also works as expected, but FileExists will hang in this situation again - both when used on filepath as well as on newfilepath.
Without the DeleteFile line, the FileExists method works fine after RenameFile (false on filepath and true on newfilepath).

Has this behaviour been recognized before?

Thanks and best regards
Kai

**Comment by Bassman2** [comment]
Hi Kai,

my library is only a .net wrapper for the COM interface of the Windows MTP implementation and should not be the reason for a freeze.
The Windows MTP implementation uses a big cache which makes some timing problems.
Check if a close and reconnect of the device will fix your problem.

Regards
  Ralf

**Comment by kiloecho2** [comment]
Hi Ralf,

thanks for the answer. I guess you are right. It's either related to the Win MTP implementation or even the one in Android.
Close and reconnect resolves the issue until the next DeleteFile operation.
In my application, I am now temporarly renaming the files that need to be deleted or replaced and then delete them in a bunch before closing the connection. That's fine enough.
Thanks for your help

Kai
