### ISSUE TITLE
Macos / Avalonia issue: COM not supported

### ISSUE THREAD

**Issue by FloridaMatt** [Bassman2/MediaDevices#31]
Apologies in advance, I'm struggling to grok all of this.  Anyway, I have a very small test project using the Avalonian UI (which I've used before to create windows/mac common source projects).  This one works fine on windows, and doesn't on macos.  
Note on loading project on the mac, I get the message:
 /Users/t/Documents/Projects/Tm2/Tm2.csproj: Warning NU1701: Package 'MediaDevices 1.8.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project. (NU1701) (Tm2)

in debug, the statement "var devices = MediaDevice.GetDevices();"
produces a System.TypeInitialization Exception with an innerexception of {System.PlatformNotSupportedException: COM is not supported}

**Comment by Bassman2** [comment]
MediaDevices is a .NET wrapper for the Windows MTP COM interface. This is only available on Windows. So MediaDevices does not work on Linux and Mac.
