### ISSUE TITLE
NotImplementedException in .NetCore 3.1 

### ISSUE THREAD

**Issue by iDanielD** [Bassman2/MediaDevices#32]
Hey,

I am working on a program to manage pictures on a mobile device. So far everything works fine and I love this NuGet. But I noticed that in .NetCore 3.1 the functions "DownloadFile" and "DownloadFileFromPersistentUniqueId" get a "NotImplementedException". I have already seen that enantiomer2000 started an issue for this, but it was not answered / fixed.
So please could you take a look at it.
Thanks in advance. 
-Daniel

**Comment by Bassman2** [comment]
Should be fixed

**Comment by iDanielD** [comment]
Sorry that I didnt write back sooner, but I tried your reworked version (Thanks for that) and there is still a NotImplementedException. Here's the callstack, I hope its enough information for you. If not write me back. 
Thanks in advance again.
![NotImplementedException](https://user-images.githubusercontent.com/63862481/81054423-1cbce900-8ec7-11ea-87ac-7aa32a392bc6.png)

**Comment by Bassman2** [comment]
Seek and Stat does not work on .NET Core as they do on .NET Framework. So I create a workaround for Length to use the COM length instead of the Stream length to make a copy possible. But seek is not useable.
If someone has an idea what's the Problem please contact me.

**Comment by DeeHants** [comment]
I think you can claim a stream is not seekable using [`CanSeek`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=netcore-3.1) and just "no-op" those methods.
Alternatively, pass that property direct to the wrapped stream's `CanSeek`, which looks like it is `false` in this instance.
I'm happy to test an update if you can rebuild the `Core31` library?

**Comment by DeeHants** [comment]
FYI, pulling in the latest code (instead of the compiled library) into a core 3.1 project works. I have not made any modifications re seeking though.

**Comment by flauschi** [comment]
I'm still seeing the exception with .NetCore 3.1 and the nuget package MediaDevices 1.9.1.
