### ISSUE TITLE
Requested resource is in use

### ISSUE THREAD

**Issue by GitterHubber** [Bassman2/MediaDevices#35]
OS Win 7 x64
.Net Framework 4.5.1
MediaDevices 1.9.0 (from github)

I use 1.8.0 from Nuget first and that worked well till I hit a road block in using the function
**OpenReadFromPersistentUniqueId()**

Now I'm using 1.9.0, with worked will for an hour or so, and then i'm getting this exception.

![image](https://user-images.githubusercontent.com/2816034/82327914-c094b180-99fc-11ea-8961-f8fbeb6b4256.png)

I can manually access images and videos on the Camera via windows explorer.
I tried restarted the computer, however that didn't change anything.

**Comment by GitterHubber** [comment]
I rechecked and found that the sd card on the camera would not allow files to be deleted. I had to format the SD card. If I remember correctly while testing the code it had crashed at some point after which this error occured.
Probably that error caused the card to go in an invalid state.

**Comment by Bassman2** [comment]
MediaDevices is a .NET wrapper for the Windows MTP COM interface. 0x800700AA is a COM error and no MediaDevices bug.
