### ISSUE TITLE
Restored using .NET Framework 4.6.1 instead of .NET Core 2.2

### ISSUE THREAD

**Issue by PoLaKoSz** [Bassman2/MediaDevices#37]
Hi!

Thank You for this great library!

I would like to use the NuGet package (**1.8.0**) in a .NET Core 2.2 application but i get this warning:

> D:\GitHub\\---\\---.csproj : warning NU1701: Package 'MediaDevices 1.8.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

I am not really familiar with multi-targeting but could this be fixed with that so NuGet could automatically restore as a .NET Core 2.1 library instead of a .NET Framework 4.6.1?

_I added this repository as a submodule to temporary fix this warning._

**Comment by Bassman2** [comment]
This is all already prepared as you can see at MediaDevices / Nuget / MediaDevices.nuspec. I just want to fix a few little things before I put a new version on Nuget. Until then, you are welcome to download the finished files from MediaDevices / Signed /.

**Comment by PoLaKoSz** [comment]
Thank You for the quick response!

**Comment by Bip901** [comment]
Getting a similar warning in .NET 5.0. `MediaDevices / Signed /` seems to be missing and the package on Nuget was last updated in January 2019. Where can I find the .NET 5.0 compatible package?
