### ISSUE TITLE
Is it possibe to monitor the gallary?

### ISSUE THREAD

**Issue by iDanielD** [Bassman2/MediaDevices#38]
Hey Bassman,

I have once again a question about your NuGet. Is there a way to monitor the gallary for changes, like adding an Image or deleting one?

Thanks in advance,
Daniel

**Comment by Bassman2** [comment]
Hi Daniel,

check the events of the MediaDevice class.

Regards
 Ralf

**Comment by iDanielD** [comment]
All right, it didn't work in my current project, because I probably used it wrong. I have now tested it in a separate project and it works perfectly. Thanks for your quick response!
