### ISSUE TITLE
Is MediaDevice.GetDevices thread safe

### ISSUE THREAD

**Issue by hualiao** [Bassman2/MediaDevices#40]
I has two device, when I call MediaDevice.GetDevices in a task the second device will become null. If I call in the same thread context MediaDevice.GetDevices return value is normal.

Test code:

       
        private static readonly object _lock_pad = new object();

        private void Test()
        {
            // second device is null
            var devices = MediaDevice.GetDevices();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Task.Run(() =>
            {
                lock (_lock_pad)
                {
                    for (var i = 0; i < 5; i++)
                    {
                        Test();
                    }
                }
            });
            
            lock (_lock_pad)
            {
                for (var i = 0; i < 10; i++)
                {
                   // when click alwarys normal return value
                    var devices = MediaDevice.GetDevices();                    
                }
            }
        }

It alse throw exception int Output window says:

System.Runtime.InteropServices.COMException (0x800706F4): 向占位程序传送了空的索引指针。 (异常来自 HRESULT:0x800706F4)
   在 MediaDevices.Internal.IPortableDeviceManager.GetDeviceDescription(String pszPnPDeviceID, StringBuilder pDeviceDescription, UInt32& pcchDeviceDescription)
   在 MediaDevices.MediaDevice..ctor(String deviceId)
System.Runtime.InteropServices.COMException (0x800706F4): 向占位程序传送了空的索引指针。 (异常来自 HRESULT:0x800706F4)
   在 MediaDevices.Internal.IPortableDeviceManager.GetDeviceFriendlyName(String pszPnPDeviceID, StringBuilder pDeviceFriendlyName, UInt32& pcchDeviceFriendlyName)
   在 MediaDevices.MediaDevice..ctor(String deviceId)
System.Runtime.InteropServices.COMException (0x800706F4): 向占位程序传送了空的索引指针。 (异常来自 HRESULT:0x800706F4)
   在 MediaDevices.Internal.IPortableDeviceManager.GetDeviceManufacturer(String pszPnPDeviceID, StringBuilder pDeviceManufacturer, UInt32& pcchDeviceManufacturer)
   在 MediaDevices.MediaDevice..ctor(String deviceId)

'向占位程序传送了空的索引指针' may translate as 'a null reference pointer was passed to the stub'

.Net Framework 4.7.2
MediaDevices 1.8.0
Thanks!

**Comment by Bassman2** [comment]
MediaDevices is a .NET wrapper for the Windows MTP COM interface. 
Since this COM interface is not thread-safe, MediaDevices is not.

**Comment by hualiao** [comment]
Sorry I don't  family with COM, I feel confuse because it is a static method. Thanks your reply.
