### ISSUE TITLE
DownloadFolder strips first character

### ISSUE THREAD

**Issue by wotandamm** [Bassman2/MediaDevices#5]
After  UploadFolder call the names of the containing folders in the first level are missing 1st character.

**Comment by Bassman2** [comment]
Thanks for your feedback. 
Your problem is not reproducible on my MTP devices. 
On which MTP device does the problem occur?

**Comment by wotandamm** [comment]
Hi Ralf,

 

I tested with a windows10 64 Bit Enterprise, a microsoft  lumia 950 and a Sony xperia Z4 Tablet.

The uploaded root folder is ok. All files and folders in the 1 first level have missing 1st charachter.

 

this is my code

 

dir1 = dev.EnumerateDirectories(@"Phone", "Elab");
dev.UploadFolder(@"c:\temp\Elab\", @"Phone\TestFolder\", true);
 


 

f1 shows the root folder with the uploaded folder TestFolder , ok

f2 shows the two folders iunside TestFolder, it should be Fehlerapp and Sicherheitsapp, not ok

f3 shows the folders and files inside ehlerapp, ok

 

Of course, the files in c:\temp\Elab are ok!

 

This happens yesterday and today on the microsoft lumia 950.

The sony xperia works today, but not yesterday.

 

strange.

 

 


Gesendet: Dienstag, 09. Januar 2018 um 06:31 Uhr
Von: "Ralf Beckers" <notifications@github.com>
An: Bassman2/MediaDevices <MediaDevices@noreply.github.com>
Cc: wotandamm <wotandamm@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [Bassman2/MediaDevices] DownloadFolder strips first character (#5)


Thanks for your feedback.
Your problem is not reproducible on my MTP devices.
On which MTP device does the problem occur?

**Comment by wotandamm** [comment]
Hi Ralf,

 

I found the problem. 

 

device.DownloadFolder(@"\Interner gemeins. Speicher\Elab\", @"c:\temp\Elab1");

 

it was the terminating backslash in source string. If I delete it, it works.

Now there is another problem.

 

device.DeleteDirectory(elab, true);

// make changes in Data

device.UploadFolder(@"c:\temp\Elab1", elab);

 

The programs hangs in the UploadFolder till I disconnect the MTP Device (Sony Xperia Z4).

How is the correct usage of DeleteDirectory and UploadFolder ?

 

 

 

Von: Ralf Beckers [mailto:notifications@github.com] 
Gesendet: Dienstag, 9. Januar 2018 06:31
An: Bassman2/MediaDevices <MediaDevices@noreply.github.com>
Cc: wotandamm <wotandamm@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Bassman2/MediaDevices] DownloadFolder strips first character (#5)

 

Thanks for your feedback.
Your problem is not reproducible on my MTP devices.
On which MTP device does the problem occur?

**Comment by Bassman2** [comment]
Fixed
