### ISSUE TITLE
NotImplementedException on console in .NetCore 3.1 project

### ISSUE THREAD

**Issue by flauschi** [Bassman2/MediaDevices#61]
**Describe the bug**
I'm using the plugin to copy files from a connected USB camera to disk. Everything works great. But for each file I try to copy to the disk, I get a NotImplementedException printed on the console. The program is not interrupted and each file seems to be copied correctly. But I'm unsure if there are any further downsides?

Exception:
`System.NotImplementedException: The method or operation is not implemented.
   at System.Runtime.InteropServices.ComTypes.IStream.Seek(Int64 dlibMove, Int32 dwOrigin, IntPtr plibNewPosition)
   at MediaDevices.Internal.StreamWrapper.Seek(Int64 offset, SeekOrigin origin)`

**To Reproduce**
The following code snippet logs the exception on console:
`Device.DownloadFile(filePathOld, filePathNew);`

It also happens if I implement the streamwriter on my own.

**Expected behavior**
There shouldn't be an exception on the console.

**Device**
Microsoft Windows 10 21H1 64bit

**Version:**
MediaDevices 1.9.1 (NuGet package)

**Additional context**
IDE: Visual Studio Community 2019
Project: .NetCore 3.1
Target platform: win-x64

**Comment by Bassman2** [comment]
Hi Robert,

please double check that all calls to MediaDevices are from the same Thread.
The underlying COM component is not thread save.

Regards,
  Ralf

**Comment by Bassman2** [comment]
OK, I can reproduce it. It only occures in core and later but not in framework.

**Comment by Bassman2** [comment]
Fixed and tested.
