### ISSUE TITLE
CopyThumbnail cause exception when copy an none Thumbnail media file like .rmvb

### ISSUE THREAD

**Issue by Acgnu** [Bassman2/MediaDevices#64]
**Describe the bug**
System.Reflection.TargetInvocationException 
COMException: 没有群集资源。 (异常来自 HRESULT:0x8007138E)

**To Reproduce**
call method CopyThumbnail on an none thumbnail file such as .rmvb video file, will cause Exception

**Expected behavior**
no exception

**Device**
Samsung galaxy Note 10, SM-N9700, Android 10

**Version:**
1.9.1

**Additional context**
Consider add a method to check the file has thumbnail or not

**Comment by Bassman2** [comment]
This is only a .NET wrapper for the Windows MTP library. So I cannot add any new functions which did not exists in the Windows MTP library.
