### ISSUE TITLE
Can not connect again after call method 'MediaDevice.DeleteFile'

### ISSUE THREAD

**Issue by Acgnu** [Bassman2/MediaDevices#65]
**Describe the bug**
call device.connect() will wait forever after call 'MediaDevice.DeleteFile', and windows explorer can not show any disk and file. it will be recover after pull out device from computer

**To Reproduce**
device.Connect();
device.DeleteFile("Any file exists in device");
device.Disconnect();

**Expected behavior**
can call device.connect() again and windows exploer can work correctly

**Device**
Samsung Galaxy Note 10, SM-N9700, Android 10

**Version:**
1.9.1

**Additional context**
Regards

**Comment by Bassman2** [comment]
The internal refreshing of the cache takes a very long time. Please retest with version 1.10 and disabled cache.

**Comment by Acgnu** [comment]
> The internal refreshing of the cache takes a very long time. Please retest with version 1.10 and disabled cache.

Problem still exists after upgrade to 1.10 and .NET Framework 4.8.1.

use device.Connect(enableCache: false)
