### ISSUE TITLE
Using GetFileInfo for each file is in efficient

### ISSUE THREAD

**Issue by ajcsoftware** [Bassman2/MediaDevices#66]
Is there a way to get a list of files with the size and date info for each because calling GetFileInfo for each file is very slow?

**Comment by raguilar127** [comment]
@ajcsoftware You should be able to use `GetDirectoryInfo("\\path\).EnumerateFiles()`. If you only need specific properties, you can use linq to Select them like `files.Select(f => new {f.Name, f.Length, f.LastWriteTime})`.

**Comment by Bassman2** [comment]
Thanks raguilar127 for the reply. I feel the same way.
