### ISSUE TITLE
Not an issue but rather a thank you

### ISSUE THREAD

**Issue by jchristn** [Bassman2/MediaDevices#71]
I published a console app using your library which helps back up contents of a media device (iPhone) to another storage repository.  Anyone that wants to use it as reference or as a baseline for their own app, please feel free to do so.  https://github.com/jchristn/PhotoSync

Thank you so much for producing this outstanding library!

**Comment by James-Ashwood** [comment]
Same here, using it in Photo Organiser Pro -https://github.com/James-Ashwood/Photo-Organiser-Pro

Great Library 😄

**Comment by Bassman2** [comment]
Thank you for your praise. With pleasure.
