### ISSUE TITLE
Reusing the same MemoryStream object for UploadFile throws COMException with HRESULT 0x800704C7

### ISSUE THREAD

**Issue by voodoo84** [Bassman2/MediaDevices#73]
**Problematic scenario:**
1) Create a byte[] array of fixed length and populate it with some pattern
2) Create a MemoryStream object with that byte[] array as a backing buffer
3) Invoke MediaDevice.UploadFile multiple times using the same MemoryStream object (but diffferent destination file name)

**Result:** Every invocation after the first throws COMException with HRESULT 0x800704C7.

**No-problem scenario:**
1) Create a byte[] array of fixed length and populate it with some pattern
2) Invoke MediaDevice.UploadFile multiple times using the new MemoryStream object each time, but backed by the very same byte[] array.

**Result:** Everything works fine.

I use the second scenario as a workaround, but there might be some COM object marshaling problems in the library (I'm not familiar with COM interop).

Tested with MediaDevices 1.9.1, .NET 4.7.2, x86 profile, Windows 10 21H2 and Samsung Galaxy J5.

**Comment by Bassman2** [comment]
Have you tried to set the MemoryStream position back to the beginning?
memStream.Seek(0, SeekOrigin.Begin);

**Comment by voodoo84** [comment]
You are right, it works. I thought that UploadFile does it automatically because it uploads the entire stream content.
In any case, this is non-issue, thanks!
