### ISSUE TITLE
Slow performance when using UploadFile with MemoryStream

### ISSUE THREAD

**Issue by tommaier123** [Bassman2/MediaDevices#75]
Hello, 
I have noticed that using a MemoryStream with UploadFile is about 10 times slower than using a filestream. In below example I am copying 500 5MB files to an MTP device either with a FileStream or with a MemoryStream. Note that the FileStream is converted to the MemoryStream in both cases so the conversion time does not matter.
```
            var devices = MediaDevice.GetDevices();

            if (devices.Count() > 0)
            {
                var device = devices.First();
                device.Connect();

                var stopwatch = new System.Diagnostics.Stopwatch();
                stopwatch.Start();
                foreach (var file in Directory.GetFiles(@"C:\TestFiles"))
                {
                    string filename = Path.GetFileName(file);
                    Console.WriteLine(filename);
                    MemoryStream ms = new MemoryStream();
                    FileStream fs = File.OpenRead(file);
                    fs.CopyTo(ms);
                    ms.Position = 0;
                    fs.Position = 0;
                    //uncomment one to test
                    //device.UploadFile(ms, Path.Combine(@"Internal shared storage\TestFiles", filename));
                    //device.UploadFile(fs, Path.Combine(@"Internal shared storage\TestFiles", filename));
                    ms.Close();
                    fs.Close();
                }
                stopwatch.Stop();
                Console.WriteLine(stopwatch.Elapsed);
            }
```
For my usecase I need to use memory streams is there a possible workaround?

**Comment by tommaier123** [comment]
I have found one workaround: writing the memory stream to a file and then reading that into a file stream. This is almost as fast as using the filestream directly but it does depend more on drive speed.

**Comment by Bassman2** [comment]
MemoryStream stores the entire stream in memory. If you don't initialize it with the file size, the memory will increase with each loop run in CopyTo, which of course costs computing time. I don't know why you want to use MemoryStream since FileStream is already buffered. But try "new MemoryStream(fileSize)".

**Comment by tommaier123** [comment]
I have tried using ```MemoryStream ms = new MemoryStream((int)fs.Length);``` instead but the result is the same.
Because I am creating a new MemoryStream each loop iteration and closing it again, that should not be the issue.
The reason I am using MemoryStream in the first place is that in my application the files get downloaded from the web and saved directly to the MTP device. I want to avoid putting them on the file system first if possible.
