### ISSUE TITLE
Expose writing Stream on MediaFileInfo

### ISSUE THREAD

**Issue by LittleLightCz** [Bassman2/MediaDevices#78]
Would it be possible to add `Stream OpenWrite()` method to the `MediaFileInfo` class in the same fashion as the `Stream OpenRead()` is? That would allow us e.g. to use `CopyToAsync()` for writing to the MTP device.

I am working on abstraction in my project which uses pure Streams for both download/upload transfers across multiple types of devices, so currently I will need to find some workaround, since only the `void UploadFile(Stream stream, string path)` is available at the moment (as far as I searched the library code).

**Comment by Bassman2** [comment]
MediaDevices is a wrapper for the Windows MTP implementation. This implementation is based on COM and is not thread safe. It is therefore not advisable to call the methods from different threads. It may work in individual cases but can lead to strange effects that are then difficult to localize. Therefore, unfortunately, do not use async here.
