### ISSUE TITLE
Checksum

### ISSUE THREAD

**Issue by SteelDragon348** [Bassman2/MediaDevices#81]
I would like to be able to Checksum a given file in a given location.  Can this be part of the MediaFileInfo class?  I tried to implement this but I was not successful.

**Comment by Bassman2** [comment]
MediaDevices is a wrapper for the Windows MTP implementation. Checksum is not part of it and thus has no place here.

For your own implementation have a look here: https://stackoverflow.com/questions/10520048/calculate-md5-checksum-for-a-file
